import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";


import Nav from './navbar/layout';
import Contact from './contact/layout';


const geistSans = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Inter({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Profile",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Nav/>
        {children}
        <Contact/>
      </body>
    </html>
  );
}
